### ISSUE TITLE
OCF release 21.3 dead lock

### ISSUE THREAD

**Issue by YamboZhou** [Open-CAS/ocf#556] opened 2021-08-18 03:12 UTC
Dear all,

We use OCF release 21.3 for our own software stack. Here is a dead lock bug. 

OCF will lock waiters list lock when it unlocks read/write request. The issue is that it will resume previous request that is waiting in waiters list and this request will try to lock the same lock of waiters list. So this is a dead lock. 
**lock waiters list -> resume requests in waiters list -> lock waiters list -> dead lock.** 

I think it should use the following steps:
**lock waiters list -> record requests in waiters list -> unlock waiters list -> resume requests -> lock waiter list -> do something of these requests -> unlock waiter list**

Could you please see whether we can completely resolve this issue use the following patch?
https://github.com/YamboZhou/ocf/commit/3d46c949ad5a02a73b3f55bab446f30198d26ac8

**Comment by mmichal10** [comment] 2021-08-18 11:06
Hi @YamboZhou, 

thank you reporting the issue. Could you please clarify whether it was discovered by code review or by testing?

**Comment by gaowayne** [comment] 2021-08-18 13:02
@robertbaldyga could you please follow up ASAP. dead lock can be reproduced from customer side. please check this and and review yambo patch. 👍

**Comment by mmichal10** [comment] 2021-08-19 06:19
Hi @YamboZhou 

thank you for reporting the issue. Our team is working on it

**Comment by gaowayne** [comment] 2021-08-19 11:03
@robertbaldyga @Deixx guys
now for reader lock, previously we use LBA to do hash, then decided which lock to pick. now we just pick next lock to get. if there is any risk with this?

```
static inline unsigned ocf_metadata_concurrency_next_idx(ocf_queue_t q)
{
	return q->lock_idx++ % OCF_NUM_GLOBAL_META_LOCKS;
}
```

**Comment by mmichal10** [comment] 2021-08-19 12:00
> dead lock can be reproduced from customer side

@gaowayne can you provide us stacktrace?

**Comment by gaowayne** [comment] 2021-08-19 12:33
@YamboZhou do you have any stack trace to share for the deadlock debug?

**Comment by gaowayne** [comment] 2021-08-19 12:35
@robertbaldyga @Deixx @mmichal10 
for example, req1 and req2, these two requests point to the same LBA range, but for the same LBA range, current code logic take different lock, this cannot protect the write on this LBA range.
```
static inline unsigned ocf_metadata_concurrency_next_idx(ocf_queue_t q)
{
	return q->lock_idx++ % OCF_NUM_GLOBAL_META_LOCKS;
}
```
please help analysis this.

**Comment by mmichal10** [comment] 2021-08-19 13:34
> OCF will lock waiters list lock when it unlocks read/write request. The issue is that it will resume previous request that is waiting in waiters list and this request will try to lock the same lock of waiters list. 

@YamboZhou before a cache line is actually being unlocked we check if it has any waiters registered. If so we grant the lock to the first waiter in the list (the lock is simply reassigned) and resume processing request associated with the waiter. Since the lock has been granted explicitly we don't have to worry about acquiring it for the second time thus we know the resumed request won't try to register a new waiter. 

However if you provide us stack trace with the deadlock we're eager to help.

**Comment by YamboZhou** [comment] 2021-08-23 06:59
@mmichal10 I have sent you email for stack trace.

**Closed** 2021-08-25 08:24 UTC
Labels: bug, P0-critical
